# packages in addition to repo2docker/buildpacks/conda/environment.yml
name: pangeo
channels:
  - conda-forge
dependencies:
  - jupyterlab=1
  - jupyterhub=1
  - nbgitpuller=0
  - dask=2
  - distributed=2
  - dask-gateway=0
  - tornado=6
  - jupyter-server-proxy=1
  - bokeh=1
  - graphviz=2
  - pip=19
  - pip:
    - git+https://github.com/jacobtomlinson/dask-kubernetes.git@spec-cluster
    - git+https://github.com/ian-r-rose/dask-labextension.git@de-asyncify#egg=dask_labextension
